package org.bitbuckets.drive;

public enum DriveFSM {

    UNINITIALIZED,
    TELEOP_NORMAL,
    TELEOP_APPROACHING_CS,
    TELEOP_BALANCING,
    TELEOP_BALANCE_ENGAGED,
    TELEOP_AUTOHEADING,
    AUTO_PATHFINDING,
    AUTO_BALANCING,

    PID_TUNING,
    AUTO_NORMAL,
    PID_TUNING1


}
