package org.bitbuckets.RGB;

import com.ctre.phoenix.ErrorCode;
import com.ctre.phoenix.led.CANdle;
import com.ctre.phoenix.led.CANdleConfiguration;
import com.ctre.phoenix.led.CANdleFaults;
import com.ctre.phoenix.led.RainbowAnimation;
import org.bitbuckets.lib.log.Debuggable;

public class RgbSubsystem {

    final CANdle candle;

    RgbFSM state = RgbFSM.ENABLED;

    final Debuggable debuggable;

    public RgbSubsystem(CANdle candle, Debuggable debuggable) {
        this.candle = candle;
        this.debuggable = debuggable;
    }

    public void robotPeriodic() {

        switch (state) {
            case DISABLED:
                ;
            case ENABLED:


                CANdleConfiguration config = new CANdleConfiguration();
                config.stripType = CANdle.LEDStripType.RGB; // set the strip type to RGB

                config.brightnessScalar = 1; // dim the LEDs to half brightness
                candle.configAllSettings(config);
                candle.setLEDs(255, 255, 255); // set the CANdle LEDs to white
                // create a rainbow animation:
                // - max brightness
                // - half speed
                // - 64 LEDs

                RainbowAnimation rainbowAnim = new RainbowAnimation(1, 1, 68);
                candle.animate(rainbowAnim);
                ErrorCode error = candle.getLastError(); // gets the last error generated by the CANdle
                CANdleFaults faults = new CANdleFaults();
                ErrorCode faultsError = candle.getFaults(faults); // fills faults with the current CANdle faults; returns the last error generated

        }

    }


}
