package org.bitbuckets.rgb;

import com.ctre.phoenix.led.CANdle;
import org.bitbuckets.OperatorInput;
import org.bitbuckets.lib.debug.IDebuggable;

public class RgbSubsystem {

    final CANdle candle;

    RgbFSM state = RgbFSM.A;

    final OperatorInput rgbInput;


    final IDebuggable debuggable;

    public RgbSubsystem(CANdle candle, OperatorInput rgbInput, IDebuggable debuggable) {
        this.candle = candle;
        this.rgbInput = rgbInput;
        this.debuggable = debuggable;
    }


    public void robotPeriodic() {

        //TODO add rgb back with real buttons and states
        /*switch (state) {
            case DISABLED:
                ;
            case A:
                if (rgbInput.is()) {
                    state = RgbFSM.B;
                    break;
                }
                RainbowAnimation rainbowAnim = new RainbowAnimation(1, 1, 68);
                candle.animate(rainbowAnim);
                ErrorCode error = candle.getLastError(); // gets the last error generated by the CANdle
                CANdleFaults faults = new CANdleFaults();
                ErrorCode faultsError = candle.getFaults(faults); // fills faults with the current CANdle faults; returns the last error generated
                break;
            case B:
                if (rgbInput.buttonA()) {
                    state = RgbFSM.A;
                    break;
                }
                LarsonAnimation larsonAnimation = new LarsonAnimation(255, 1, 1, 1, 1, 68, LarsonAnimation.BounceMode.Center, 2);
                candle.animate(larsonAnimation);
                break;
        }*/

    }


}
